---
AWSTemplateFormatVersion: "2010-09-09"

Description: This template creates a vpc with public and private subnet

Metadata:


Parameters:
  VpcCIDR:
    Default: 10.0.0.0/16
    Description: Please enter the ip range of vpc
    Type: String

  Publicsubnet1CIDR:
    Default: 10.0.0.0/24
    Description: Please enter the ip range of public subnet1
    Type: String

  Publicsubnet2CIDR:
    Default: 10.0.1.0/24
    Description: Please enter the ip range of public subnet2
    Type: String

  Privatesubnet1CIDR:
    Default: 10.0.2.0/24
    Description: Please enter the ip range of private subnet1
    Type: String

  Privatesubnet2CIDR:
    Default: 10.0.3.0/24
    Description: Please enter the ip range of private subnet2
    Type: String

  Privatesubnet3CIDR:
    Default: 10.0.4.0/24
    Description: Please enter the ip range of private subnet3
    Type: String

  Privatesubnet4CIDR:
    Default: 10.0.5.0/24
    Description: Please enter the ip range of private subnet4
    Type: String
    
  SSHLocation:
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: The IP address range that can be used to access the web server using SSH.
    MaxLength: '18'
    MinLength: '9'
    Type: String

#creating Vpc
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default                      #dedeicated/default
      Tags: 
        - Key: Name
          Value: Test VPC

#creating Internet Gateway

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: Test IGW

#Creating a IGW Attachment
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

#creating publicsubnet1
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select [ 0, listOfObjects ]
      CidrBlock: String
      EnableDns64: Boolean
      Ipv6CidrBlock: String
      Ipv6Native: Boolean
      MapPublicIpOnLaunch: Boolean
      OutpostArn: String
      PrivateDnsNameOptionsOnLaunch: Json
      Tags: 
        - Tag
      VpcId: String





Outputs:

